services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wishlist-bot
    restart: always
    ports:
      - '3000:3000'
    environment:
     - DATABASE_URL=postgresql://wishlist:keregindiallostonyou@db:5432/wishlistdb
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: wishlist
      POSTGRES_PASSWORD: keregindiallostonyou
      POSTGRES_DB: wishlistdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
